# Generated by Django 4.1.3 on 2022-11-21 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_art_image_alter_mycart_added_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycart',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 18, 57, 7, 202626)),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 18, 57, 7, 202626)),
        ),
    ]
